<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Title>Chow</Title>
        <Authors>Sebastian Bathrick</Authors>
        <RepositoryType></RepositoryType>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Copyright>Copyright © 2026 Sebastian Bathrick</Copyright>
        <Version>0.1.32</Version>
        <AssemblyName>Chow</AssemblyName>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Chow.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
