<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Title>Chow</Title>
        <Authors>Sebastian Bathrick</Authors>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Copyright>Copyright © 2026 Sebastian Bathrick</Copyright>
        <Version>0.2.0-preview</Version>
        <AssemblyName>Chow</AssemblyName>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
        <Description>A Python sublanguage interpreter written entirely in C# for embedding in .NET projects. It provides a sandboxed scripting environment featuring OOP, LEGB-enforced scope, closures, and more. Chow targets .NET Standard 2.0 and has no external dependencies.
</Description>
        <RepositoryUrl>https://github.com/SebastianBathrick/Chow</RepositoryUrl>
        <PackageTags>python embedded scripting interop oop</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Chow.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
